# Generated by Django 6.0 on 2026-01-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите электронную почту",
                        max_length=254,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Введите ФИО", verbose_name="Ф.И.О."),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
            ],
        ),
    ]
