# Generated by Django 6.0 on 2026-01-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recipient",
        ),
    ]
